metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 5s
  reload.enabled: true

processors:
  - add_docker_metadata: ~

monitoring.enabled: true
setup.ilm.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  
logging.to_files: false

# setup:
#   kibana.host: "kibana:5601"
#   dashboards.enabled: true